name: maptec
description: Aplicación que te muestra como llegar a los departamentos del TecNM
  Campus Cuautla.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.3.5'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity_plus: ^3.0.2
  background_location_tracker: ^1.3.1
  flutter_local_notifications: ^9.9.0
  package_info_plus: ^3.0.2
  flutter_cached_pdfview: ^0.4.1
  flutter_map: ^3.0.0
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^4.1.1
  geolocator: ^9.0.2
  http: ^0.13.5
  latlong2: ^0.8.1
  permission_handler: ^10.2.0
  provider: ^6.0.4
  rxdart: ^0.27.5
  sqflite: ^2.2.0+3
  url_launcher: ^6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/pdf/

    - assets/image/
    - assets/image/edificios/

    - assets/image/mapa/16/14759/
    - assets/image/mapa/16/14760/
    - assets/image/mapa/16/14761/

    - assets/image/mapa/17/29518/
    - assets/image/mapa/17/29519/
    - assets/image/mapa/17/29520/
    - assets/image/mapa/17/29521/
    - assets/image/mapa/17/29522/

    - assets/image/mapa/18/59037/
    - assets/image/mapa/18/59038/
    - assets/image/mapa/18/59039/
    - assets/image/mapa/18/59040/
    - assets/image/mapa/18/59041/
    - assets/image/mapa/18/59042/
    - assets/image/mapa/18/59043/
    - assets/image/mapa/18/59044/
    - assets/image/mapa/18/59045/